### ISSUE TITLE
Grant access to the MATLAB and Simulink Integration for GitHub

### ISSUE THREAD

**Issue by ehennestad** [openMetadataInitiative/openMINDS_MATLAB#8]
https://se.mathworks.com/matlabcentral/discussions/highlights/847426?s_tid=side_fx_announce

@olinux @lzehl

**Comment by olinux** [comment]
Hi,
I think it should be ok to install it - however I would solely grant access to the openMINDS_MATLAB repository. If this is fine with @lzehl I can go ahead with the installation of the plugin.

**Comment by lzehl** [comment]
@olinux I agree with this restriction @ehennestad fine with me then.

**Comment by ehennestad** [comment]
I also agree with @olinux, there is no need to grant access to any of the other repositories.
